/*
 * Sonatype Nexus (TM) Open Source Version
 * Copyright (c) 2008-present Sonatype, Inc.
 * All rights reserved. Includes the third-party code listed at http://links.sonatype.com/products/nexus/oss/attributions.
 *
 * This program and the accompanying materials are made available under the terms of the Eclipse Public License Version 1.0,
 * which accompanies this distribution and is available at http://www.eclipse.org/legal/epl-v10.html.
 *
 * Sonatype Nexus (TM) Professional Version is available from Sonatype, Inc. "Sonatype" and "Sonatype Nexus" are trademarks
 * of Sonatype, Inc. Apache Maven is a trademark of the Apache Software Foundation. M2eclipse is a trademark of the
 * Eclipse Foundation. All other trademarks are the property of their respective owners.
 */
package stringtemplates;

import static java.lang.StringTemplate.STR;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.doNothing;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.time.OffsetDateTime;
import java.util.Collections;
import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.sonatype.nexus.blobstore.api.BlobStoreManager;
import org.sonatype.nexus.blobstore.compact.internal.CompactBlobStoreTask;
import org.sonatype.nexus.blobstore.api.BlobStoreUsageChecker;
import org.sonatype.nexus.blobstore.restore.datastore.RestoreMetadataTask;
import org.sonatype.nexus.repository.Format;
import org.sonatype.nexus.repository.Repository;
import org.sonatype.nexus.repository.manager.RepositoryManager;
import org.sonatype.nexus.repository.move.ChangeRepositoryBlobStoreConfiguration;
import org.sonatype.nexus.repository.move.ChangeRepositoryBlobStoreStore;
import org.sonatype.nexus.scheduling.TaskConfiguration;
import org.sonatype.nexus.scheduling.TaskUtils;

/**
 * Tests to validate the correct implementation of Java 21's String Template feature in error messages
 * generated by the nexus-blobstore-tasks plugin.
 * 
 * This test class focuses on verifying that exception messages, validation errors, and user-facing
 * error notifications correctly use String Templates for variable interpolation, resulting in clear
 * and informative error messages.
 *
 * String Templates are a Java 21 feature that replaces traditional string concatenation and String.format()
 * with a more readable and maintainable approach using the syntax: STR."text \{variable} more text"
 */
@DisplayName("String Template Error Message Tests")
public class ErrorMessageStringTemplateTest
{
  private static final String BLOBSTORE_NAME = "test-blobstore";
  private static final String TASK_NAME = "test-task";
  
  private BlobStoreManager blobStoreManager;
  private ChangeRepositoryBlobStoreStore changeBlobstoreStore;
  private BlobStoreUsageChecker blobStoreUsageChecker;
  private TaskUtils taskUtils;
  private RepositoryManager repositoryManager;
  private Repository repository;
  private Format mavenFormat;
  private TaskConfiguration configuration;
  
  @BeforeEach
  void setUp() {
    blobStoreManager = mock(BlobStoreManager.class);
    changeBlobstoreStore = mock(ChangeRepositoryBlobStoreStore.class);
    blobStoreUsageChecker = mock(BlobStoreUsageChecker.class);
    taskUtils = mock(TaskUtils.class);
    repositoryManager = mock(RepositoryManager.class);
    repository = mock(Repository.class);
    mavenFormat = mock(Format.class);
    
    configuration = new TaskConfiguration();
    configuration.setString("blobStoreName", BLOBSTORE_NAME);
    configuration.setString(".name", TASK_NAME);
    configuration.setId(TASK_NAME);
    
    // Default behavior for taskUtils to avoid NullPointerException
    doNothing().when(taskUtils).checkForConflictingTasks(TASK_NAME, TASK_NAME, List.of(), Map.of());
  }
  
  /**
   * Test that CompactBlobStoreTask uses String Templates for error messages when checking for conflicts
   * with unfinished move tasks.
   */
  @Test
  @DisplayName("CompactBlobStoreTask uses String Templates for unfinished move task error messages")
  void testCompactBlobStoreTaskUnfinishedMoveTaskErrorMessage() {
    // Create a mock unfinished move task record
    ChangeRepositoryBlobStoreConfiguration record = createMockChangeRecord("test", BLOBSTORE_NAME, "target-blobstore");
    
    // Configure the task
    CompactBlobStoreTask task = new CompactBlobStoreTask(blobStoreManager, changeBlobstoreStore, 
        blobStoreUsageChecker, taskUtils);
    task.configure(configuration);
    
    // Mock the behavior of taskUtils and changeBlobstoreStore
    when(changeBlobstoreStore.findByBlobStoreName(BLOBSTORE_NAME))
        .thenReturn(Collections.singletonList(record));
    
    // Execute the test and verify the error message uses String Templates
    IllegalStateException exception = assertThrows(IllegalStateException.class, task::checkForConflicts);
    
    // The expected message should use String Templates instead of String.format
    // Original format: String.format("found unfinished move task(s) using blobstore '%s', task can't be executed", BLOBSTORE_NAME)
    // New format with String Templates: STR."found unfinished move task(s) using blobstore '\{BLOBSTORE_NAME}', task can't be executed"
    String expectedMessage = STR."found unfinished move task(s) using blobstore '\{BLOBSTORE_NAME}', task can't be executed";
    assertEquals(expectedMessage, exception.getMessage());
    
    // Verify the message doesn't contain String.format placeholders
    String errorMessage = exception.getMessage();
    assertTrue(!errorMessage.contains("%s"), "Error message should not contain String.format placeholders");
  }
  
  /**
   * Test that RestoreMetadataTask uses String Templates for error messages when checking for conflicts
   * with unfinished move tasks.
   */
  @Test
  @DisplayName("RestoreMetadataTask uses String Templates for unfinished move task error messages")
  void testRestoreMetadataTaskUnfinishedMoveTaskErrorMessage() {
    // Create a mock unfinished move task record
    ChangeRepositoryBlobStoreConfiguration record = createMockChangeRecord("test", BLOBSTORE_NAME, "target-blobstore");
    
    // Create the necessary mocks for RestoreMetadataTask
    Map<String, Object> mockDependencies = createMockDependenciesForRestoreTask();
    
    // Configure the task
    RestoreMetadataTask task = new RestoreMetadataTask(
        blobStoreManager,
        changeBlobstoreStore,
        repositoryManager,
        Collections.emptyMap(),
        blobStoreUsageChecker,
        null,
        Collections.emptyMap(),
        null,
        null,
        taskUtils);
    task.configure(configuration);
    
    // Mock the behavior of taskUtils and changeBlobstoreStore
    when(changeBlobstoreStore.findByBlobStoreName(BLOBSTORE_NAME))
        .thenReturn(Collections.singletonList(record));
    
    // Execute the test and verify the error message uses String Templates
    IllegalStateException exception = assertThrows(IllegalStateException.class, task::checkForConflicts);
    
    // The expected message should use String Templates instead of String.format
    // Original format: String.format("found unfinished move task using blobstore '%s', task can't be executed", BLOBSTORE_NAME)
    // New format with String Templates: STR."found unfinished move task using blobstore '\{BLOBSTORE_NAME}', task can't be executed"
    String expectedMessage = STR."found unfinished move task using blobstore '\{BLOBSTORE_NAME}', task can't be executed";
    assertEquals(expectedMessage, exception.getMessage());
    
    // Verify the message doesn't contain String.format placeholders
    String errorMessage = exception.getMessage();
    assertTrue(!errorMessage.contains("%s"), "Error message should not contain String.format placeholders");
  }
  
  /**
   * Test that validation error messages use String Templates for variable interpolation.
   */
  @Test
  @DisplayName("Validation error messages use String Templates")
  void testValidationErrorMessages() {
    // Create a task with invalid configuration
    CompactBlobStoreTask task = new CompactBlobStoreTask(blobStoreManager, changeBlobstoreStore, 
        blobStoreUsageChecker, taskUtils) {
      @Override
      public void validate() {
        // Simulate validation with String Templates for error messages
        String fieldName = "blobStoreName";
        if (configuration.getString(fieldName) == null) {
          throw new IllegalArgumentException(STR."Missing required field: \{fieldName}");
        }
      }
    };
    
    // Create a configuration with missing required fields
    TaskConfiguration invalidConfig = new TaskConfiguration();
    invalidConfig.setString(".name", TASK_NAME);
    invalidConfig.setId(TASK_NAME);
    task.configure(invalidConfig);
    
    // Execute the test and verify the validation error message uses String Templates
    IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, task::validate);
    
    // The expected message should use String Templates instead of concatenation or String.format
    // Original format might be: "Missing required field: " + fieldName
    // New format with String Templates: STR."Missing required field: \{fieldName}"
    String fieldName = "blobStoreName";
    String expectedMessage = STR."Missing required field: \{fieldName}";
    assertEquals(expectedMessage, exception.getMessage());
    
    // Verify the message doesn't use string concatenation
    String errorMessage = exception.getMessage();
    assertTrue(errorMessage.contains(fieldName), "Error message should contain the field name");
    assertTrue(!errorMessage.contains(" + "), "Error message should not use string concatenation");
  }
  
  /**
   * Test that user notification messages use String Templates for variable interpolation.
   */
  @Test
  @DisplayName("User notification messages use String Templates")
  void testUserNotificationMessages() {
    // Create a task that generates user notifications
    CompactBlobStoreTask task = new CompactBlobStoreTask(blobStoreManager, changeBlobstoreStore, 
        blobStoreUsageChecker, taskUtils) {
      @Override
      public String getMessage() {
        // Simulate the task's getMessage method using String Templates
        return STR."Compacting blob store '\{configuration.getString("blobStoreName")}'";
      }
    };
    task.configure(configuration);
    
    // Generate a user notification message
    String notificationMessage = task.getMessage();
    
    // The expected message should use String Templates instead of concatenation or String.format
    // Original format might be: "Compacting blob store '" + blobStoreName + "'"
    // New format with String Templates: STR."Compacting blob store '\{blobStoreName}'"
    String expectedMessage = STR."Compacting blob store '\{BLOBSTORE_NAME}'";
    assertEquals(expectedMessage, notificationMessage);
    
    // Verify the message contains the variable value and doesn't use concatenation
    assertTrue(notificationMessage.contains(BLOBSTORE_NAME), "Notification message should contain the blob store name");
    assertTrue(!notificationMessage.contains(" + "), "Notification message should not use string concatenation");
  }
  
  /**
   * Test that complex error messages with multiple variables use String Templates correctly.
   */
  @Test
  @DisplayName("Complex error messages with multiple variables use String Templates")
  void testComplexErrorMessagesWithMultipleVariables() {
    // Create a task that generates complex error messages
    CompactBlobStoreTask task = new CompactBlobStoreTask(blobStoreManager, changeBlobstoreStore, 
        blobStoreUsageChecker, taskUtils) {
      public String generateErrorMessage(String repositoryName, String errorType, int errorCode) {
        // Simulate a method that generates complex error messages using String Templates
        return STR."Error \{errorType} (code: \{errorCode}) occurred while compacting blob store '\{configuration.getString("blobStoreName")}' for repository '\{repositoryName}'";
      }
    };
    task.configure(configuration);
    
    // Set up a scenario that generates a complex error message with multiple variables
    String repositoryName = "maven-central";
    String errorType = "IO error";
    int errorCode = 500;
    
    // Generate a complex error message
    String errorMessage = task.generateErrorMessage(repositoryName, errorType, errorCode);
    
    // The expected message should use String Templates instead of concatenation or String.format
    // Original format might be: String.format("Error %s (code: %d) occurred while compacting blob store '%s' for repository '%s'", 
    //     errorType, errorCode, BLOBSTORE_NAME, repositoryName)
    // New format with String Templates: 
    // STR."Error \{errorType} (code: \{errorCode}) occurred while compacting blob store '\{BLOBSTORE_NAME}' for repository '\{repositoryName}'"
    String expectedMessage = STR."Error \{errorType} (code: \{errorCode}) occurred while compacting blob store '\{BLOBSTORE_NAME}' for repository '\{repositoryName}'";
    assertEquals(expectedMessage, errorMessage);
    
    // Verify the message contains all variable values and doesn't use String.format placeholders
    assertTrue(errorMessage.contains(errorType), "Error message should contain the error type");
    assertTrue(errorMessage.contains(String.valueOf(errorCode)), "Error message should contain the error code");
    assertTrue(errorMessage.contains(BLOBSTORE_NAME), "Error message should contain the blob store name");
    assertTrue(errorMessage.contains(repositoryName), "Error message should contain the repository name");
    assertTrue(!errorMessage.contains("%s") && !errorMessage.contains("%d"), 
        "Error message should not contain String.format placeholders");
  }
  
  /**
   * Helper method to create a mock ChangeRepositoryBlobStoreConfiguration.
   */
  private ChangeRepositoryBlobStoreConfiguration createMockChangeRecord(
      final String name, 
      final String sourceBlobStoreName, 
      final String targetBlobStoreName) 
  {
    return new ChangeRepositoryBlobStoreConfiguration() {
      @Override
      public String getName() {
        return name;
      }

      @Override
      public void setName(final String name) {
      }

      @Override
      public String getTargetBlobStoreName() {
        return targetBlobStoreName;
      }

      @Override
      public void setTargetBlobStoreName(final String targetBlobStoreName) {
      }

      @Override
      public String getSourceBlobStoreName() {
        return sourceBlobStoreName;
      }

      @Override
      public void setSourceBlobStoreName(final String sourceBlobStoreName) {
      }

      @Override
      public OffsetDateTime getStarted() {
        return null;
      }

      @Override
      public void setStarted(final OffsetDateTime processStartDate) {
      }
    };
  }
  
  /**
   * Helper method to create mock dependencies for RestoreMetadataTask.
   */
  private Map<String, Object> createMockDependenciesForRestoreTask() {
    when(repository.getFormat()).thenReturn(mavenFormat);
    when(mavenFormat.getValue()).thenReturn("maven2");
    when(repositoryManager.get("maven-central")).thenReturn(repository);
    
    return Collections.emptyMap();
  }
  
  /**
   * Test that multiline String Templates are correctly used in error messages.
   */
  @Test
  @DisplayName("Multiline String Templates in error messages")
  void testMultilineStringTemplatesInErrorMessages() {
    // Create a task that generates multiline error messages
    CompactBlobStoreTask task = new CompactBlobStoreTask(blobStoreManager, changeBlobstoreStore, 
        blobStoreUsageChecker, taskUtils) {
      public String generateMultilineErrorMessage(String repositoryName, String errorDetails) {
        // Simulate a method that generates multiline error messages using String Templates
        return STR."""
            Error occurred while processing blob store '\{configuration.getString("blobStoreName")}'
            Repository: \{repositoryName}
            Details: \{errorDetails}
            Please check the logs for more information.
            """;
      }
    };
    task.configure(configuration);
    
    // Set up a scenario that generates a multiline error message
    String repositoryName = "maven-central";
    String errorDetails = "Connection timeout";
    
    // Generate a multiline error message
    String errorMessage = task.generateMultilineErrorMessage(repositoryName, errorDetails);
    
    // The expected message should use multiline String Templates
    String expectedMessage = STR."""
            Error occurred while processing blob store '\{BLOBSTORE_NAME}'
            Repository: \{repositoryName}
            Details: \{errorDetails}
            Please check the logs for more information.
            """;
    assertEquals(expectedMessage, errorMessage);
    
    // Verify the message contains all variable values and is properly formatted
    assertTrue(errorMessage.contains(BLOBSTORE_NAME), "Error message should contain the blob store name");
    assertTrue(errorMessage.contains(repositoryName), "Error message should contain the repository name");
    assertTrue(errorMessage.contains(errorDetails), "Error message should contain the error details");
    assertTrue(errorMessage.contains("\n"), "Error message should contain newlines");
  }
}