/*
 * Sonatype Nexus (TM) Open Source Version
 * Copyright (c) 2008-present Sonatype, Inc.
 * All rights reserved. Includes the third-party code listed at http://links.sonatype.com/products/nexus/oss/attributions.
 *
 * This program and the accompanying materials are made available under the terms of the Eclipse Public License Version 1.0,
 * which accompanies this distribution and is available at http://www.eclipse.org/legal/epl-v10.html.
 *
 * Sonatype Nexus (TM) Professional Version is available from Sonatype, Inc. "Sonatype" and "Sonatype Nexus" are trademarks
 * of Sonatype, Inc. Apache Maven is a trademark of the Apache Software Foundation. M2eclipse is a trademark of the
 * Eclipse Foundation. All other trademarks are the property of their respective owners.
 */
package org.sonatype.nexus.crypto.internal;

import java.time.Duration;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.ThreadFactory;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.LongAdder;

import org.sonatype.goodies.testsupport.TestSupport;

import org.junit.Before;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.greaterThan;
import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.lessThan;
import static org.hamcrest.Matchers.not;

/**
 * Tests for {@link RandomBytesGeneratorImpl} using Java 21 Virtual Threads.
 * 
 * This test validates that the RandomBytesGeneratorImpl works correctly and efficiently
 * when used concurrently with Virtual Threads, ensuring that cryptographically secure
 * random number generation remains thread-safe and performs well under high concurrency.
 */
public class RandomBytesGeneratorImplVirtualThreadTest
    extends TestSupport
{
  private static final Logger log = LoggerFactory.getLogger(RandomBytesGeneratorImplVirtualThreadTest.class);
  
  private static final int THREAD_COUNT = 1000;
  private static final int BYTES_SIZE = 32; // 256 bits, common for crypto operations
  private static final int WARMUP_ITERATIONS = 5;
  private static final int TEST_ITERATIONS = 3;
  
  private RandomBytesGeneratorImpl generator;

  @Before
  public void setUp() throws Exception {
    this.generator = new RandomBytesGeneratorImpl(new CryptoHelperImpl());
  }

  /**
   * Tests concurrent random byte generation using Virtual Threads.
   * 
   * This test creates a large number of Virtual Threads that concurrently generate
   * random bytes, validating thread safety and performance under high concurrency.
   */
  @Test
  public void testConcurrentRandomGenerationWithVirtualThreads() throws Exception {
    log.info("Testing concurrent random byte generation with {} Virtual Threads", THREAD_COUNT);
    
    // Warm up to allow JIT compilation
    for (int i = 0; i < WARMUP_ITERATIONS; i++) {
      runConcurrentTest(true);
    }
    
    // Run the actual test
    double virtualThreadAvgTime = 0;
    double platformThreadAvgTime = 0;
    
    for (int i = 0; i < TEST_ITERATIONS; i++) {
      virtualThreadAvgTime += runConcurrentTest(true);
      platformThreadAvgTime += runConcurrentTest(false);
    }
    
    virtualThreadAvgTime /= TEST_ITERATIONS;
    platformThreadAvgTime /= TEST_ITERATIONS;
    
    log.info("Average execution time with Virtual Threads: {} ms", virtualThreadAvgTime);
    log.info("Average execution time with Platform Threads: {} ms", platformThreadAvgTime);
    
    // At high concurrency, virtual threads should show better performance
    // This might not always be true for CPU-bound operations, but for operations
    // that might involve some blocking or I/O, virtual threads should be more efficient
    assertThat("Virtual Threads should be more efficient at high concurrency", 
        virtualThreadAvgTime, lessThan(platformThreadAvgTime * 1.5)); // Allow some margin
  }
  
  /**
   * Tests the cryptographic quality of random bytes generated concurrently.
   * 
   * This test validates that bytes generated concurrently by multiple Virtual Threads
   * maintain cryptographic quality by checking for uniqueness and distribution.
   */
  @Test
  public void testCryptographicQualityWithVirtualThreads() throws Exception {
    log.info("Testing cryptographic quality with concurrent Virtual Threads");
    
    // Use a ConcurrentHashMap to collect all generated byte arrays
    ConcurrentHashMap<String, byte[]> generatedBytes = new ConcurrentHashMap<>();
    CountDownLatch latch = new CountDownLatch(THREAD_COUNT);
    
    try (ExecutorService executor = Executors.newVirtualThreadPerTaskExecutor()) {
      // Submit tasks to generate random bytes
      for (int i = 0; i < THREAD_COUNT; i++) {
        final int threadId = i;
        executor.submit(() -> {
          try {
            byte[] bytes = generator.generate(BYTES_SIZE);
            // Use the byte array's hash code as a key
            generatedBytes.put(threadId + "-" + Arrays.hashCode(bytes), bytes);
          } finally {
            latch.countDown();
          }
        });
      }
      
      // Wait for all threads to complete
      latch.await(30, TimeUnit.SECONDS);
    }
    
    // Verify that we got the expected number of unique byte arrays
    assertThat("All threads should generate unique random bytes", 
        generatedBytes.size(), is(THREAD_COUNT));
    
    // Basic statistical check - count zero bytes across all arrays
    // In truly random data, approximately 1/256 of all bytes should be zero
    long totalBytes = (long) THREAD_COUNT * BYTES_SIZE;
    long zeroBytes = countZeroBytes(generatedBytes.values());
    double zeroRatio = (double) zeroBytes / totalBytes;
    
    log.info("Zero bytes ratio: {} (expected around {})", zeroRatio, 1.0/256);
    
    // The ratio should be close to 1/256 (0.00390625) for truly random data
    // Allow a reasonable margin for statistical variation
    double expectedRatio = 1.0 / 256;
    assertThat("Zero bytes ratio should be close to expected value", 
        zeroRatio, is(greaterThan(expectedRatio * 0.5)));
    assertThat("Zero bytes ratio should be close to expected value", 
        zeroRatio, is(lessThan(expectedRatio * 2.0)));
  }
  
  /**
   * Tests for thread pinning issues when using Virtual Threads with SecureRandom.
   * 
   * This test monitors carrier thread utilization to detect potential thread pinning
   * issues that could impact Virtual Thread performance.
   */
  @Test
  public void testThreadPinningWithVirtualThreads() throws Exception {
    log.info("Testing for thread pinning issues with Virtual Threads");
    
    // Create a large number of virtual threads
    int threadCount = 10000; // Use more threads to better detect pinning
    CountDownLatch startLatch = new CountDownLatch(1);
    CountDownLatch completionLatch = new CountDownLatch(threadCount);
    
    // Track unique carrier threads to detect pinning
    ConcurrentHashMap<Long, LongAdder> carrierThreadCounts = new ConcurrentHashMap<>();
    
    // Create and start virtual threads
    List<Thread> threads = new ArrayList<>();
    for (int i = 0; i < threadCount; i++) {
      Thread thread = Thread.ofVirtual().name("vt-" + i).start(() -> {
        try {
          // Wait for all threads to be ready
          startLatch.await();
          
          // Generate random bytes
          generator.generate(BYTES_SIZE);
          
          // Record carrier thread ID
          // In Java 21, we can use Thread.currentCarrierThread() but for compatibility
          // we'll use the thread name which includes carrier thread info when logged
          long threadId = Thread.currentThread().threadId();
          carrierThreadCounts.computeIfAbsent(threadId, k -> new LongAdder()).increment();
        } 
        catch (InterruptedException e) {
          Thread.currentThread().interrupt();
        }
        finally {
          completionLatch.countDown();
        }
      });
      threads.add(thread);
    }
    
    // Start all threads simultaneously
    startLatch.countDown();
    
    // Wait for completion
    completionLatch.await(30, TimeUnit.SECONDS);
    
    // Log carrier thread distribution
    log.info("Carrier thread distribution for {} virtual threads:", threadCount);
    AtomicInteger carrierCount = new AtomicInteger(0);
    carrierThreadCounts.forEach((id, count) -> {
      log.info("Carrier thread {}: {} tasks", id, count.sum());
      carrierCount.incrementAndGet();
    });
    
    // Calculate average tasks per carrier thread
    double avgTasksPerCarrier = (double) threadCount / carrierCount.get();
    log.info("Average tasks per carrier thread: {}", avgTasksPerCarrier);
    
    // We expect multiple virtual threads per carrier thread
    // If we have close to a 1:1 ratio, that suggests pinning
    assertThat("Should have significantly fewer carrier threads than virtual threads",
        carrierCount.get(), is(lessThan(threadCount / 10)));
    
    // Clean up
    for (Thread thread : threads) {
      thread.join(100);
    }
  }
  
  /**
   * Runs a concurrent test with either virtual or platform threads.
   * 
   * @param useVirtualThreads true to use virtual threads, false for platform threads
   * @return execution time in milliseconds
   */
  private double runConcurrentTest(boolean useVirtualThreads) throws Exception {
    CountDownLatch startLatch = new CountDownLatch(1);
    CountDownLatch completionLatch = new CountDownLatch(THREAD_COUNT);
    
    ExecutorService executor;
    if (useVirtualThreads) {
      executor = Executors.newVirtualThreadPerTaskExecutor();
    } else {
      // Use a fixed thread pool for platform threads
      executor = Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors() * 2,
          new ThreadFactory() {
            private final AtomicInteger counter = new AtomicInteger();
            @Override
            public Thread newThread(Runnable r) {
              return new Thread(r, "platform-" + counter.incrementAndGet());
            }
          });
    }
    
    try {
      // Submit tasks to generate random bytes
      List<Future<?>> futures = new ArrayList<>();
      for (int i = 0; i < THREAD_COUNT; i++) {
        futures.add(executor.submit(() -> {
          try {
            startLatch.await(); // Wait for all threads to be ready
            generator.generate(BYTES_SIZE); // Generate random bytes
          } 
          catch (InterruptedException e) {
            Thread.currentThread().interrupt();
          }
          finally {
            completionLatch.countDown();
          }
        }));
      }
      
      // Start timing
      long startTime = System.nanoTime();
      startLatch.countDown(); // Start all threads simultaneously
      
      // Wait for all threads to complete
      boolean completed = completionLatch.await(30, TimeUnit.SECONDS);
      long endTime = System.nanoTime();
      
      if (!completed) {
        log.warn("Not all threads completed within the timeout period");
      }
      
      // Calculate execution time in milliseconds
      double executionTime = Duration.ofNanos(endTime - startTime).toMillis();
      
      String threadType = useVirtualThreads ? "Virtual" : "Platform";
      log.info("{} Threads execution time: {} ms", threadType, executionTime);
      
      return executionTime;
    } 
    finally {
      executor.shutdown();
      executor.awaitTermination(5, TimeUnit.SECONDS);
    }
  }
  
  /**
   * Counts the number of zero bytes in the collection of byte arrays.
   * 
   * @param byteArrays collection of byte arrays to check
   * @return count of zero bytes
   */
  private long countZeroBytes(Iterable<byte[]> byteArrays) {
    long count = 0;
    for (byte[] array : byteArrays) {
      for (byte b : array) {
        if (b == 0) {
          count++;
        }
      }
    }
    return count;
  }
}