<!--

    Sonatype Nexus (TM) Open Source Version
    Copyright (c) 2008-present Sonatype, Inc.
    All rights reserved. Includes the third-party code listed at http://links.sonatype.com/products/nexus/oss/attributions.

    This program and the accompanying materials are made available under the terms of the Eclipse Public License Version 1.0,
    which accompanies this distribution and is available at http://www.eclipse.org/legal/epl-v10.html.

    Sonatype Nexus (TM) Professional Version is available from Sonatype, Inc. "Sonatype" and "Sonatype Nexus" are trademarks
    of Sonatype, Inc. Apache Maven is a trademark of the Apache Software Foundation. M2eclipse is a trademark of the
    Eclipse Foundation. All other trademarks are the property of their respective owners.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.sonatype.nexus.buildsupport</groupId>
    <artifactId>nexus-buildsupport</artifactId>
    <version>3.77.0-08</version>
  </parent>

  <artifactId>nexus-buildsupport-httpclient</artifactId>
  <name>${project.groupId}:${project.artifactId}</name>
  <packaging>pom</packaging>

  <properties>
    <httpclient5.version>5.3.1</httpclient5.version>
    <httpcore5.version>5.2.5</httpcore5.version>
    <httpmime5.version>5.3.1</httpmime5.version>
</properties>

<dependencyManagement>
    <dependencies>

        <dependency>
            <groupId>org.apache.hc.client5</groupId>
            <artifactId>httpclient5</artifactId>
            <version>${httpclient5.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.apache.hc.client5</groupId>
            <artifactId>httpclient5-fluent</artifactId>
            <version>${httpclient5.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.hc.client5</groupId>
            <artifactId>httpmime5</artifactId>
            <version>${httpmime5.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.hc.core5</groupId>
            <artifactId>httpcore5</artifactId>
            <version>${httpcore5.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.hc.core5</groupId>
            <artifactId>httpcore5-h2</artifactId>
            <version>${httpcore5.version}</version>
        </dependency>

    </dependencies>
</dependencyManagement>
</project>
